services:
  redis:
    image: redis:7
    container_name: chidi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./chidi-backend/services/api-gateway
      dockerfile: Dockerfile
    container_name: chidi-api-gateway
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./chidi-backend/services/api-gateway:/app

volumes:
  redis_data:
