services:
  redis:
    image: redis:7
    container_name: chidi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./chidi-backend
      dockerfile: services/api-gateway/Dockerfile
    container_name: chidi-api-gateway
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      # Supabase environment variables
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      # Database URL will come from Supabase
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # Mount both service and shared code for development
      - ./chidi-backend/services/api-gateway/app:/app/app
      - ./chidi-backend/shared:/app/shared

volumes:
  redis_data:
